export const lemmaMap = new Map([
    // Verbs (to be)
    ['is', 'be'], ['was', 'be'], ['are', 'be'], ['were', 'be'], ['being', 'be'], ['been', 'be'],
    // Verbs (common)
    ['looked', 'look'], ['looks', 'look'], ['looking', 'look'],
    ['smiled', 'smile'], ['smiles', 'smile'], ['smiling', 'smile'],
    ['seemed', 'seem'], ['seems', 'seem'], ['seeming', 'seem'],
    ['felt', 'feel'], ['feels', 'feel'], ['feeling', 'feel'],
    ['said', 'say'], ['says', 'say'], ['saying', 'say'],
    ['went', 'go'], ['goes', 'go'], ['going', 'go'],
    ['had', 'have'], ['has', 'have'], ['having', 'have'],
    ['did', 'do'], ['does', 'do'], ['doing', 'do'],
    ['knew', 'know'], ['knows', 'know'], ['knowing', 'know'],
    ['took', 'take'], ['takes', 'take'], ['taking', 'take'],
    ['saw', 'see'], ['sees', 'see'], ['seeing', 'see'],
    ['came', 'come'], ['comes', 'come'], ['coming', 'come'],
    ['thought', 'think'], ['thinks', 'think'], ['thinking', 'think'],
    ['gave', 'give'], ['gives', 'give'], ['giving', 'give'],
    ['told', 'tell'], ['tells', 'tell'], ['telling', 'tell'],
    ['made', 'make'], ['makes', 'make'], ['making', 'make'],
    ['used', 'use'], ['uses', 'use'], ['using', 'use'],
    ['worked', 'work'], ['works', 'work'], ['working', 'work'],
    ['wanted', 'want'], ['wants', 'want'], ['wanting', 'want'],
    ['asked', 'ask'], ['asks', 'ask'], ['asking', 'ask'],
    ['tried', 'try'], ['tries', 'try'], ['trying', 'try'],
    ['called', 'call'], ['calls', 'call'], ['calling', 'call'],
    ['needed', 'need'], ['needs', 'need'], ['needing', 'need'],
    ['turned', 'turn'], ['turns', 'turn'], ['turning', 'turn'],
    ['started', 'start'], ['starts', 'start'], ['starting', 'start'],
    ['played', 'play'], ['plays', 'play'], ['playing', 'play'],
    ['moved', 'move'], ['moves', 'move'], ['moving', 'move'],
    ['lived', 'live'], ['lives', 'live'], ['living', 'live'],
    ['believed', 'believe'], ['believes', 'believe'], ['believing', 'believe'],
    ['happened', 'happen'], ['happens', 'happen'], ['happening', 'happen'],
    ['wrote', 'write'], ['writes', 'write'], ['writing', 'write'],
    ['provided', 'provide'], ['provides', 'provide'], ['providing', 'provide'],
    ['sat', 'sit'], ['sits', 'sit'], ['sitting', 'sit'],
    ['stood', 'stand'], ['stands', 'stand'], ['standing', 'stand'],
    ['lost', 'lose'], ['loses', 'lose'], ['losing', 'lose'],
    ['paid', 'pay'], ['pays', 'pay'], ['paying', 'pay'],
    ['met', 'meet'], ['meets', 'meet'], ['meeting', 'meet'],
    ['included', 'include'], ['includes', 'include'], ['including', 'include'],
    ['continued', 'continue'], ['continues', 'continue'], ['continuing', 'continue'],
    ['set', 'set'], ['setting', 'set'],
    ['learned', 'learn'], ['learns', 'learn'], ['learning', 'learn'],
    ['changed', 'change'], ['changes', 'change'], ['changing', 'change'],
    ['led', 'lead'], ['leads', 'lead'], ['leading', 'lead'],
    ['understood', 'understand'], ['understands', 'understand'], ['understanding', 'understand'],
    ['watched', 'watch'], ['watches', 'watch'], ['watching', 'watch'],
    ['followed', 'follow'], ['follows', 'follow'], ['following', 'follow'],
    ['stopped', 'stop'], ['stops', 'stop'], ['stopping', 'stop'],
    ['created', 'create'], ['creates', 'create'], ['creating', 'create'],
    ['spoke', 'speak'], ['speaks', 'speak'], ['speaking', 'speak'],
    ['read', 'read'], ['reads', 'read'], ['reading', 'read'],
    ['allowed', 'allow'], ['allows', 'allow'], ['allowing', 'allow'],
    ['added', 'add'], ['adds', 'add'], ['adding', 'add'],
    ['spent', 'spend'], ['spends', 'spend'], ['spending', 'spend'],
    ['grew', 'grow'], ['grows', 'grow'], ['growing', 'grow'],
    ['opened', 'open'], ['opens', 'open'], ['opening', 'open'],
    ['walked', 'walk'], ['walks', 'walk'], ['walking', 'walk'],
    ['won', 'win'], ['wins', 'win'], ['winning', 'win'],
    ['offered', 'offer'], ['offers', 'offer'], ['offering', 'offer'],
    ['remembered', 'remember'], ['remembers', 'remember'], ['remembering', 'remember'],
    ['loved', 'love'], ['loves', 'love'], ['loving', 'love'],
    ['considered', 'consider'], ['considers', 'consider'], ['considering', 'consider'],
    ['appeared', 'appear'], ['appears', 'appear'], ['appearing', 'appear'],
    ['bought', 'buy'], ['buys', 'buy'], ['buying', 'buy'],
    ['waited', 'wait'], ['waits', 'wait'], ['waiting', 'wait'],
    ['served', 'serve'], ['serves', 'serve'], ['serving', 'serve'],
    ['died', 'die'], ['dies', 'die'], ['dying', 'die'],
    ['sent', 'send'], ['sends', 'send'], ['sending', 'send'],
    ['expected', 'expect'], ['expects', 'expect'], ['expecting', 'expect'],
    ['stayed', 'stay'], ['stays', 'stay'], ['staying', 'stay'],
    ['fell', 'fall'], ['falls', 'fall'], ['falling', 'fall'],
    ['reached', 'reach'], ['reaches', 'reach'], ['reaching', 'reach'],
    ['killed', 'kill'], ['kills', 'kill'], ['killing', 'kill'],
    ['remained', 'remain'], ['remains', 'remain'], ['remaining', 'remain'],
    ['suggested', 'suggest'], ['suggests', 'suggest'], ['suggesting', 'suggest'],
    ['raised', 'raise'], ['raises', 'raise'], ['raising', 'raise'],
    ['passed', 'pass'], ['passes', 'pass'], ['passing', 'pass'],
    ['sold', 'sell'], ['sells', 'sell'], ['selling', 'sell'],
    ['required', 'require'], ['requires', 'require'], ['requiring', 'require'],
    ['reported', 'report'], ['reports', 'report'], ['reporting', 'report'],
    ['decided', 'decide'], ['decides', 'decide'], ['deciding', 'decide'],
    ['pulled', 'pull'], ['pulls', 'pull'], ['pulling', 'pull'],
    // Nouns (common plurals)
    ['eyes', 'eye'], ['years', 'year'], ['ways', 'way'], ['days', 'day'], ['hands', 'hand'],
    ['words', 'word'], ['things', 'thing'], ['times', 'time'], ['lips', 'lip'], ['cheeks', 'cheek'],
    ['shoulders', 'shoulder'], ['arms', 'arm'], ['legs', 'leg'], ['fingers', 'finger'],
    ['thoughts', 'thought'], ['moments', 'moment'], ['steps', 'step'], ['features', 'feature'],
    ['voices', 'voice'], ['rooms', 'room'], ['doors', 'door'], ['walls', 'wall'],
    ['tears', 'tear'], ['fears', 'fear'], ['hopes', 'hope'], ['dreams', 'dream'],
]);